// <auto-generated />
namespace Launchpad.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RoleClaims_Table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RoleClaims_Table));
        
        string IMigrationMetadata.Id
        {
            get { return "201610281946586_RoleClaims_Table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
