// <auto-generated />
namespace Launchpad.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class LaunchpadLog_Fix_ColumnTypes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LaunchpadLog_Fix_ColumnTypes));
        
        string IMigrationMetadata.Id
        {
            get { return "201611102152561_LaunchpadLog_Fix_ColumnTypes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
